### ISSUE TITLE
Can I get a test dataset?

### ISSUE THREAD

**Issue by pangfumin** [skrogh/msf_ekf#5]
Hi @skrogh ,
Thank you for sharing this code, it's a succinct and clean implement  of the MSF.
I wonder could you please provide a test dataset you used in Main_test.cpp?
 I will be very grateful if you can provide.

Thank you again.

Pang @Beijing

**Comment by skrogh** [comment]
I'm sorry.
The project is rather old and I do no longer have the files that are not stored here on GitHub
